# Site settings
title:          "'অনি'লেখা"
description:    "ভাবনার আঁকিবুঁকি"
url:            "https://anilekhon.github.io"

# Google Analytics
google_analytics: G-19L958VFF2

# Author
author:
  name:         অনিকেত
  # url:          https://chester.how
  email:        aniketpramanick26@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
